export default {
    LOAD_CONFIGURATION_REQUEST: 'LOAD_CONFIGURATION_REQUEST',
    LOAD_CONFIGURATION_ERROR: 'LOAD_CONFIGURATION_ERROR',
    LOAD_CONFIGURATION_SUCCESS: 'LOAD_CONFIGURATION_SUCCESS',
    UPDATE_CONFIGURATION_REQUEST: 'UPDATE_CONFIGURATION_REQUEST',
    UPDATE_CONFIGURATION_ERROR: 'UPDATE_CONFIGURATION_ERROR',
    UPDATE_CONFIGURATION_SUCCESS: 'UPDATE_CONFIGURATION_SUCCESS',
    LOAD_CONFIGURATION_FORM_REQUEST: 'LOAD_CONFIGURATION_FORM_REQUEST',
    LOAD_CONFIGURATION_FORM_SUCCESS: 'LOAD_CONFIGURATION_FORM_SUCCESS',
    LOAD_CONFIGURATION_FORM_ERROR: 'LOAD_CONFIGURATION_FORM_ERROR'
};
