version: '2'
services:
  website:
    image: node:12
    container_name: website
    restart: always
    ports:
      - 7000:7000
    volumes:
      - ..:/usr/src/app
    command: sh -c "yarn install && yarn dev"