version: '2'
services:
  mwilson_website:
    extends:
      file: docker-compose.yml
      service: mwilson_website
    ports:
      - "7000:7000"
    volumes:
      - ..:/usr/src/app
    command: sh -c "yarn install && nodemon app.js"
    environment:
      - DEBUG
