version: '3.3'
services:
  traefik:
    image: traefik:v2.2
    networks:
      - mewil
    command:
      - --accesslog=true
      - --api.dashboard=true
      - --providers.docker
      - --providers.docker.network=mewil
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/run/secrets/
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entryPoints.web.http.redirections.entryPoint.to=websecure
      - --entryPoints.web.http.redirections.entryPoint.scheme=https
      - --entryPoints.web.http.redirections.entryPoint.permanent=true
      - --certificatesResolvers.le.acme.email=${LETSENCRYPT_EMAIL}
      - --certificatesResolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesResolvers.le.acme.tlschallenge=true
      - --log.level=DEBUG
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencryptdata:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - traefik.toml
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=Host(`traefik.mewil.io`)"
        - "traefik.http.routers.traefik.entrypoints=websecure"
        - "traefik.http.routers.traefik.tls.certresolver=le"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.routers.traefik.middlewares=auth-middleware"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      
  auth:
    image: thomseddon/traefik-forward-auth:2.2.0
    networks:
      - mewil
    command: --whitelist=${LETSENCRYPT_EMAIL}
    environment:
      - PROVIDERS_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - PROVIDERS_GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SECRET=${AUTH_SECRET}
      - COOKIE_DOMAIN=mewil.io
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.auth.loadbalancer.server.port=4181"
        - "traefik.http.middlewares.auth-middleware.forwardauth.address=http://auth:4181"
        - "traefik.http.middlewares.auth-middleware.forwardauth.authResponseHeaders=X-Forwarded-User"

  grafana:
    image: grafana/grafana:7.0.6
    networks:
      - mewil
    environment:
      - GF_SECURITY_ADMIN_USER=${LETSENCRYPT_EMAIL}
      - GF_SECURITY_COOKIE_SECURE=true
      - GF_AUTH_PROXY_ENABLED=true
      - GF_AUTH_PROXY_HEADER_NAME=X-Forwarded-User
      - GF_USERS_ALLOW_SIGNUP=false
      - GF_USERS_AUTO_ASSIGN_ORG=true
      - GF_LOG_MODE=console
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_DATABASE_URL=postgres://root:${POSTGRES_PASSWORD}@postgres:5432/grafana
      - GF_DATABASE_SSL_MODE=require
    volumes:
      - grafanadata:/var/lib/grafana
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grafana.rule=Host(`dashboard.mewil.io`)"
        - "traefik.http.routers.grafana.entrypoints=websecure"
        - "traefik.http.routers.grafana.tls.certresolver=le"
        - "traefik.http.routers.grafana.middlewares=auth-middleware"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  n8n:
    image: n8nio/n8n:0.79.3
    networks:
      - mewil
    volumes:
      - n8ndata:/root/.n8n
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.n8n.rule=Host(`workflows.mewil.io`)"
        - "traefik.http.routers.n8n.entrypoints=websecure"
        - "traefik.http.routers.n8n.tls.certresolver=le"
        - "traefik.http.routers.n8n.middlewares=auth-middleware"
        - "traefik.http.services.n8n.loadbalancer.server.port=5678"

  postgres:
    image: postgres:12
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB=grafana
      - POSTGRES_USER=postgres
    volumes:
      - postgresdata:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1

secrets:
  traefik.toml:
    external: true

networks:
  mewil:
    driver: overlay

volumes:
  letsencryptdata:
    external: true
  grafanadata:
    external: true
  n8ndata:
    external: true
  postgresdata:
    external: true