[http]
  [http.routers]
    [http.routers.website]
      entrypoints = ["websecure"]
      middlewares = ["indexPath"]
      rule = "Host(`mewil.io`)"
      service = "website"
      [http.routers.website.tls]
        certResolver = "le"

  [http.middlewares.indexPath.redirectRegex]
    regex = "https://mewil.io?/$"
    replacement = "https://mewil.io/index.html"
      
  [http.services]
    [http.services.website.loadBalancer]
      passHostHeader = false
      [[http.services.website.loadBalancer.servers]]
        url = "https://cdn.mewil.io"